version = 1

[[scan]]
path = "/home/muham/Projects/airgap-guardian/src/scanner"
scanners = ["jwt"]

[[scan]]
path = "/home/muham/Projects/airgap-guardian/testdata"
scanners = ["cert"]

[[scan]]
path = "/home/muham/Projects/airgap-guardian/testdata/nested"
scanners = ["cert"]

[[scan]]
path = "/home/muham/Projects/airgap-guardian/testdata/secrets"
scanners = ["secret", "jwt"]

[[scan]]
path = "/home/muham/Projects/airgap-guardian/testdata/ssh"
scanners = ["ssh"]
